### ISSUE TITLE
Problem with the item on the recycler view

### ISSUE THREAD

**Issue by Mario21145** [slendy98DX/sinnoh-pokedex#1]
### **Issue with the item**

_When i continue to click constantly the item it doesn't show me the image of the pokemon , instead if i click only one time it shows me the image_

https://github.com/slendy98DX/sinnoh-pokedex/assets/144329270/41695fe9-7ec4-4576-90fc-7f66ab293df5

**Comment by slendy98DX** [comment]
I can't seem to replicate the problem, but i added a placeholder image just in case.

**Comment by slendy98DX** [comment]
I found a solution to the problem, i fixed the issue now. I couldn't replicate it with my device, but with an emulator i could.
