### ISSUE TITLE
Margin when the image placeholder is showed 

### ISSUE THREAD

**Issue by Mario21145** [slendy98DX/sinnoh-pokedex#2]
### **Margin to add**

_**The image error for when the connection is not available is attached to the top part of the info of the pokemon**_

![fd7bcdbe-a1c5-477e-94cf-112f8557c745](https://github.com/slendy98DX/sinnoh-pokedex/assets/144329270/326f4f1d-3796-42d7-ace7-25a740231fcf)

**Comment by slendy98DX** [comment]
fixed, thank you for the insight
