### ISSUE TITLE
Landscape layout for the error connection case

### ISSUE THREAD

**Issue by Mario21145** [slendy98DX/sinnoh-pokedex#3]
**### Modify the layout**

**_The landscape layout is not very interactive and visbily beautiful , move it to the center of the screen_**

![b9602c70-428a-45b7-96db-35016fed70e3](https://github.com/slendy98DX/sinnoh-pokedex/assets/144329270/3bb3bf40-fe80-4388-8b3d-1b31feb5557b)

**Comment by slendy98DX** [comment]
I like it better the way it is, and i already added a network error image, but i forgot to commit it yesterday.
