### ISSUE TITLE
Add a placeholder for the image

### ISSUE THREAD

**Issue by Mario21145** [slendy98DX/sinnoh-pokedex#4]
### **Add a placeholder for the image loading state**

**_Add a placeholder for the image , because when it is loading show to the user an empty part of screen and its not the best option_**

![28fa3a00-5c8e-4eac-ae6c-01f3afcb51a7](https://github.com/slendy98DX/sinnoh-pokedex/assets/144329270/a6123e97-5f48-4f3c-b38b-b95cfec87c45)

**Comment by slendy98DX** [comment]
Done.
